In [7]:
import pandas as pd

In [5]:
import pandas as pd
marks = pd.Series([80, 75, 90, 65])
print(marks)

0    80
1    75
2    90
3    65
dtype: int64

# Dataframe

In [4]:
data = {
    "Name": ["John", "Alice", "Bob"],
    "Age": [20, 21, 19],
    "Marks": [85, 92, 78]
}
df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   21     92
2    Bob   19     78

In [5]:
df.head(2)

    Name  Age  Marks
0   John   20     85
1  Alice   21     92

In [6]:
df.tail(2)

    Name  Age  Marks
1  Alice   21     92
2    Bob   19     78

In [7]:
print(df.shape)

(3, 3)

In [8]:
df.describe()

        Age  Marks
count   3.0    3.0
mean   20.0   85.0
std     1.0    7.0
min    19.0   78.0
25%    19.5   81.5
50%    20.0   85.0
75%    20.5   88.5
max    21.0   92.0